# Set the language
language: node_js

# Set the Node version
node_js:
  - '14'

services:
  # Use Docker command line
  - docker

deploy:
  # Build Docker container and push to Docker Hub
  provider: script
  script: bash deploy.sh
  on:
    branch: master
